// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, title) VALUES (?, ?) RETURNING id
`

type CreateCategoryParams struct {
	UserID int64
	Title  string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.UserID, arg.Title)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = ? AND user_id = ?
`

type DeleteCategoryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, title FROM categories WHERE id = ? AND user_id = ?
`

type GetCategoryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(&i.ID, &i.UserID, &i.Title)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, title FROM categories WHERE user_id = ? ORDER BY title COLLATE NOCASE ASC
`

func (q *Queries) ListCategories(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.UserID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadCountsByCategory = `-- name: UnreadCountsByCategory :many
SELECT f.category_id AS category_id, COUNT(*) AS n
FROM entries e JOIN feeds f ON e.feed_id = f.id
WHERE e.user_id = ? AND e.status = 'unread'
GROUP BY f.category_id
`

type UnreadCountsByCategoryRow struct {
	CategoryID sql.NullInt64
	N          int64
}

func (q *Queries) UnreadCountsByCategory(ctx context.Context, userID int64) ([]UnreadCountsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, unreadCountsByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnreadCountsByCategoryRow
	for rows.Next() {
		var i UnreadCountsByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories SET title = ? WHERE id = ? AND user_id = ?
`

type UpdateCategoryParams struct {
	Title  string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategory, arg.Title, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
