// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelFeedExtractions = `-- name: CancelFeedExtractions :exec
UPDATE entries SET extract_state = 'none', next_extract_at = NULL
WHERE feed_id = ? AND extract_state = 'pending'
`

func (q *Queries) CancelFeedExtractions(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, cancelFeedExtractions, feedID)
	return err
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM entries WHERE id = ? AND user_id = ?
`

type DeleteEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, feed_id, guid, url, title, author, content, summary, published_at, status, starred, read_at, created_at, hash, extract_state, extract_attempts, next_extract_at FROM entries WHERE id = ? AND user_id = ?
`

type GetEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.PublishedAt,
		&i.Status,
		&i.Starred,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Hash,
		&i.ExtractState,
		&i.ExtractAttempts,
		&i.NextExtractAt,
	)
	return i, err
}

const getEntryByGUID = `-- name: GetEntryByGUID :one
SELECT id, hash FROM entries WHERE feed_id = ? AND guid = ?
`

type GetEntryByGUIDParams struct {
	FeedID int64
	Guid   string
}

type GetEntryByGUIDRow struct {
	ID   int64
	Hash string
}

func (q *Queries) GetEntryByGUID(ctx context.Context, arg GetEntryByGUIDParams) (GetEntryByGUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryByGUID, arg.FeedID, arg.Guid)
	var i GetEntryByGUIDRow
	err := row.Scan(&i.ID, &i.Hash)
	return i, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (user_id, feed_id, guid, url, title, author, content, summary,
  published_at, status, starred, read_at, created_at, hash, extract_state, next_extract_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'unread', 0, NULL, ?, ?, ?, ?)
RETURNING id
`

type InsertEntryParams struct {
	UserID        int64
	FeedID        int64
	Guid          string
	Url           string
	Title         string
	Author        string
	Content       string
	Summary       string
	PublishedAt   int64
	CreatedAt     int64
	Hash          string
	ExtractState  string
	NextExtractAt sql.NullInt64
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEntry,
		arg.UserID,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Summary,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.Hash,
		arg.ExtractState,
		arg.NextExtractAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTombstone = `-- name: InsertTombstone :exec
INSERT INTO tombstones (feed_id, guid, deleted_at) VALUES (?, ?, ?)
ON CONFLICT(feed_id, guid) DO UPDATE SET deleted_at = excluded.deleted_at
`

type InsertTombstoneParams struct {
	FeedID    int64
	Guid      string
	DeletedAt int64
}

func (q *Queries) InsertTombstone(ctx context.Context, arg InsertTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, insertTombstone, arg.FeedID, arg.Guid, arg.DeletedAt)
	return err
}

const listPendingExtractions = `-- name: ListPendingExtractions :many
SELECT id, user_id, feed_id, guid, url, title, author, content, summary, published_at, status, starred, read_at, created_at, hash, extract_state, extract_attempts, next_extract_at FROM entries
WHERE extract_state = 'pending' AND next_extract_at <= ?
ORDER BY published_at DESC, id DESC LIMIT ?
`

type ListPendingExtractionsParams struct {
	NextExtractAt sql.NullInt64
	Limit         int64
}

func (q *Queries) ListPendingExtractions(ctx context.Context, arg ListPendingExtractionsParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listPendingExtractions, arg.NextExtractAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.PublishedAt,
			&i.Status,
			&i.Starred,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Hash,
			&i.ExtractState,
			&i.ExtractAttempts,
			&i.NextExtractAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedEntriesPending = `-- name: MarkFeedEntriesPending :exec
UPDATE entries SET extract_state = 'pending', next_extract_at = ?
WHERE feed_id = ? AND extract_state IN ('none','failed')
`

type MarkFeedEntriesPendingParams struct {
	NextExtractAt sql.NullInt64
	FeedID        int64
}

func (q *Queries) MarkFeedEntriesPending(ctx context.Context, arg MarkFeedEntriesPendingParams) error {
	_, err := q.db.ExecContext(ctx, markFeedEntriesPending, arg.NextExtractAt, arg.FeedID)
	return err
}

const setEntryContent = `-- name: SetEntryContent :exec
UPDATE entries SET content = ?, extract_state = 'done', next_extract_at = NULL WHERE id = ?
`

type SetEntryContentParams struct {
	Content string
	ID      int64
}

func (q *Queries) SetEntryContent(ctx context.Context, arg SetEntryContentParams) error {
	_, err := q.db.ExecContext(ctx, setEntryContent, arg.Content, arg.ID)
	return err
}

const tombstoneExists = `-- name: TombstoneExists :one
SELECT 1 FROM tombstones WHERE feed_id = ? AND guid = ?
`

type TombstoneExistsParams struct {
	FeedID int64
	Guid   string
}

func (q *Queries) TombstoneExists(ctx context.Context, arg TombstoneExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tombstoneExists, arg.FeedID, arg.Guid)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateEntryContent = `-- name: UpdateEntryContent :exec
UPDATE entries SET title = ?, author = ?, content = ?, summary = ?,
  published_at = ?, url = ?, hash = ? WHERE id = ? AND user_id = ?
`

type UpdateEntryContentParams struct {
	Title       string
	Author      string
	Content     string
	Summary     string
	PublishedAt int64
	Url         string
	Hash        string
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateEntryContent(ctx context.Context, arg UpdateEntryContentParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryContent,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Summary,
		arg.PublishedAt,
		arg.Url,
		arg.Hash,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateExtractState = `-- name: UpdateExtractState :exec
UPDATE entries SET extract_state = ?, extract_attempts = ?, next_extract_at = ? WHERE id = ?
`

type UpdateExtractStateParams struct {
	ExtractState    string
	ExtractAttempts int64
	NextExtractAt   sql.NullInt64
	ID              int64
}

func (q *Queries) UpdateExtractState(ctx context.Context, arg UpdateExtractStateParams) error {
	_, err := q.db.ExecContext(ctx, updateExtractState,
		arg.ExtractState,
		arg.ExtractAttempts,
		arg.NextExtractAt,
		arg.ID,
	)
	return err
}

const weeklyEntryCount = `-- name: WeeklyEntryCount :one
SELECT COUNT(*) FROM entries
WHERE feed_id = ?1
  AND (CASE WHEN published_at > 0 THEN published_at ELSE created_at END) >= ?2
  AND (CASE WHEN published_at > 0 THEN published_at ELSE created_at END) <= ?3
`

type WeeklyEntryCountParams struct {
	FeedID      int64
	WindowStart int64
	WindowEnd   int64
}

func (q *Queries) WeeklyEntryCount(ctx context.Context, arg WeeklyEntryCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, weeklyEntryCount, arg.FeedID, arg.WindowStart, arg.WindowEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}
