// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"
)

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM entries WHERE id = ? AND user_id = ?
`

type DeleteEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, feed_id, guid, url, title, author, content, summary, published_at, status, starred, read_at, created_at, hash FROM entries WHERE id = ? AND user_id = ?
`

type GetEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.PublishedAt,
		&i.Status,
		&i.Starred,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Hash,
	)
	return i, err
}

const getEntryByGUID = `-- name: GetEntryByGUID :one
SELECT id, hash FROM entries WHERE feed_id = ? AND guid = ?
`

type GetEntryByGUIDParams struct {
	FeedID int64
	Guid   string
}

type GetEntryByGUIDRow struct {
	ID   int64
	Hash string
}

func (q *Queries) GetEntryByGUID(ctx context.Context, arg GetEntryByGUIDParams) (GetEntryByGUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryByGUID, arg.FeedID, arg.Guid)
	var i GetEntryByGUIDRow
	err := row.Scan(&i.ID, &i.Hash)
	return i, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (user_id, feed_id, guid, url, title, author, content, summary,
  published_at, status, starred, read_at, created_at, hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'unread', 0, NULL, ?, ?)
RETURNING id
`

type InsertEntryParams struct {
	UserID      int64
	FeedID      int64
	Guid        string
	Url         string
	Title       string
	Author      string
	Content     string
	Summary     string
	PublishedAt int64
	CreatedAt   int64
	Hash        string
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEntry,
		arg.UserID,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Summary,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.Hash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTombstone = `-- name: InsertTombstone :exec
INSERT INTO tombstones (feed_id, guid, deleted_at) VALUES (?, ?, ?)
ON CONFLICT(feed_id, guid) DO UPDATE SET deleted_at = excluded.deleted_at
`

type InsertTombstoneParams struct {
	FeedID    int64
	Guid      string
	DeletedAt int64
}

func (q *Queries) InsertTombstone(ctx context.Context, arg InsertTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, insertTombstone, arg.FeedID, arg.Guid, arg.DeletedAt)
	return err
}

const tombstoneExists = `-- name: TombstoneExists :one
SELECT 1 FROM tombstones WHERE feed_id = ? AND guid = ?
`

type TombstoneExistsParams struct {
	FeedID int64
	Guid   string
}

func (q *Queries) TombstoneExists(ctx context.Context, arg TombstoneExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tombstoneExists, arg.FeedID, arg.Guid)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateEntryContent = `-- name: UpdateEntryContent :exec
UPDATE entries SET title = ?, author = ?, content = ?, summary = ?,
  published_at = ?, url = ?, hash = ? WHERE id = ? AND user_id = ?
`

type UpdateEntryContentParams struct {
	Title       string
	Author      string
	Content     string
	Summary     string
	PublishedAt int64
	Url         string
	Hash        string
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateEntryContent(ctx context.Context, arg UpdateEntryContentParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryContent,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Summary,
		arg.PublishedAt,
		arg.Url,
		arg.Hash,
		arg.ID,
		arg.UserID,
	)
	return err
}
