// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, feed_url, site_url, title, description, etag, last_modified,
  disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id,
  fetch_full_content)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateFeedParams struct {
	UserID           int64
	FeedUrl          string
	SiteUrl          string
	Title            string
	Description      string
	Etag             string
	LastModified     string
	Disabled         int64
	CheckedAt        sql.NullInt64
	NextCheckAt      int64
	ErrorCount       int64
	LastError        string
	CreatedAt        int64
	UpdatedAt        int64
	CategoryID       sql.NullInt64
	FetchFullContent int64
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.UserID,
		arg.FeedUrl,
		arg.SiteUrl,
		arg.Title,
		arg.Description,
		arg.Etag,
		arg.LastModified,
		arg.Disabled,
		arg.CheckedAt,
		arg.NextCheckAt,
		arg.ErrorCount,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CategoryID,
		arg.FetchFullContent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteFeed = `-- name: DeleteFeed :execrows
DELETE FROM feeds WHERE id = ? AND user_id = ?
`

type DeleteFeedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, feed_url, site_url, title, description, etag, last_modified, disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id, fetch_full_content FROM feeds WHERE id = ? AND user_id = ?
`

type GetFeedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedUrl,
		&i.SiteUrl,
		&i.Title,
		&i.Description,
		&i.Etag,
		&i.LastModified,
		&i.Disabled,
		&i.CheckedAt,
		&i.NextCheckAt,
		&i.ErrorCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.FetchFullContent,
	)
	return i, err
}

const listDueFeeds = `-- name: ListDueFeeds :many
SELECT id, user_id, feed_url, site_url, title, description, etag, last_modified, disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id, fetch_full_content FROM feeds
WHERE disabled = 0 AND next_check_at <= ?
ORDER BY next_check_at ASC LIMIT ?
`

type ListDueFeedsParams struct {
	NextCheckAt int64
	Limit       int64
}

func (q *Queries) ListDueFeeds(ctx context.Context, arg ListDueFeedsParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listDueFeeds, arg.NextCheckAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.SiteUrl,
			&i.Title,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.Disabled,
			&i.CheckedAt,
			&i.NextCheckAt,
			&i.ErrorCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.FetchFullContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, feed_url, site_url, title, description, etag, last_modified, disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id, fetch_full_content FROM feeds WHERE user_id = ? ORDER BY title COLLATE NOCASE ASC
`

func (q *Queries) ListFeeds(ctx context.Context, userID int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.SiteUrl,
			&i.Title,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.Disabled,
			&i.CheckedAt,
			&i.NextCheckAt,
			&i.ErrorCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.FetchFullContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedCategory = `-- name: SetFeedCategory :execrows
UPDATE feeds SET category_id = ? WHERE id = ? AND user_id = ?
`

type SetFeedCategoryParams struct {
	CategoryID sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) SetFeedCategory(ctx context.Context, arg SetFeedCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedCategory, arg.CategoryID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setFeedFullContent = `-- name: SetFeedFullContent :execrows
UPDATE feeds SET fetch_full_content = ? WHERE id = ? AND user_id = ?
`

type SetFeedFullContentParams struct {
	FetchFullContent int64
	ID               int64
	UserID           int64
}

func (q *Queries) SetFeedFullContent(ctx context.Context, arg SetFeedFullContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedFullContent, arg.FetchFullContent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFeed = `-- name: UpdateFeed :exec
UPDATE feeds SET
  site_url = ?, title = ?, description = ?, etag = ?, last_modified = ?,
  disabled = ?, checked_at = ?, next_check_at = ?, error_count = ?, last_error = ?,
  updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateFeedParams struct {
	SiteUrl      string
	Title        string
	Description  string
	Etag         string
	LastModified string
	Disabled     int64
	CheckedAt    sql.NullInt64
	NextCheckAt  int64
	ErrorCount   int64
	LastError    string
	UpdatedAt    int64
	ID           int64
	UserID       int64
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeed,
		arg.SiteUrl,
		arg.Title,
		arg.Description,
		arg.Etag,
		arg.LastModified,
		arg.Disabled,
		arg.CheckedAt,
		arg.NextCheckAt,
		arg.ErrorCount,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
