// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, feed_url, site_url, title, description, etag, last_modified,
  disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id,
  fetch_full_content, ttl_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateFeedParams struct {
	UserID           int64
	FeedUrl          string
	SiteUrl          string
	Title            string
	Description      string
	Etag             string
	LastModified     string
	Disabled         int64
	CheckedAt        sql.NullInt64
	NextCheckAt      int64
	ErrorCount       int64
	LastError        string
	CreatedAt        int64
	UpdatedAt        int64
	CategoryID       sql.NullInt64
	FetchFullContent int64
	TtlSeconds       sql.NullInt64
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.UserID,
		arg.FeedUrl,
		arg.SiteUrl,
		arg.Title,
		arg.Description,
		arg.Etag,
		arg.LastModified,
		arg.Disabled,
		arg.CheckedAt,
		arg.NextCheckAt,
		arg.ErrorCount,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CategoryID,
		arg.FetchFullContent,
		arg.TtlSeconds,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteFeed = `-- name: DeleteFeed :execrows
DELETE FROM feeds WHERE id = ? AND user_id = ?
`

type DeleteFeedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const entryStatsByFeed = `-- name: EntryStatsByFeed :many
SELECT feed_id,
  COUNT(*)                                  AS total,
  COUNT(*) FILTER (WHERE status = 'unread') AS unread
FROM entries WHERE user_id = ? GROUP BY feed_id
`

type EntryStatsByFeedRow struct {
	FeedID int64
	Total  int64
	Unread int64
}

func (q *Queries) EntryStatsByFeed(ctx context.Context, userID int64) ([]EntryStatsByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, entryStatsByFeed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryStatsByFeedRow
	for rows.Next() {
		var i EntryStatsByFeedRow
		if err := rows.Scan(&i.FeedID, &i.Total, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, feed_url, site_url, title, description, etag, last_modified, disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id, fetch_full_content, ttl_seconds, user_title FROM feeds WHERE id = ? AND user_id = ?
`

type GetFeedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedUrl,
		&i.SiteUrl,
		&i.Title,
		&i.Description,
		&i.Etag,
		&i.LastModified,
		&i.Disabled,
		&i.CheckedAt,
		&i.NextCheckAt,
		&i.ErrorCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.FetchFullContent,
		&i.TtlSeconds,
		&i.UserTitle,
	)
	return i, err
}

const listDueFeeds = `-- name: ListDueFeeds :many
SELECT id, user_id, feed_url, site_url, title, description, etag, last_modified, disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id, fetch_full_content, ttl_seconds, user_title FROM feeds
WHERE disabled = 0 AND next_check_at <= ?
ORDER BY next_check_at ASC LIMIT ?
`

type ListDueFeedsParams struct {
	NextCheckAt int64
	Limit       int64
}

func (q *Queries) ListDueFeeds(ctx context.Context, arg ListDueFeedsParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listDueFeeds, arg.NextCheckAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.SiteUrl,
			&i.Title,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.Disabled,
			&i.CheckedAt,
			&i.NextCheckAt,
			&i.ErrorCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.FetchFullContent,
			&i.TtlSeconds,
			&i.UserTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, feed_url, site_url, title, description, etag, last_modified, disabled, checked_at, next_check_at, error_count, last_error, created_at, updated_at, category_id, fetch_full_content, ttl_seconds, user_title FROM feeds WHERE user_id = ? ORDER BY title COLLATE NOCASE ASC
`

func (q *Queries) ListFeeds(ctx context.Context, userID int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.SiteUrl,
			&i.Title,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.Disabled,
			&i.CheckedAt,
			&i.NextCheckAt,
			&i.ErrorCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.FetchFullContent,
			&i.TtlSeconds,
			&i.UserTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedCategory = `-- name: SetFeedCategory :execrows
UPDATE feeds SET category_id = ? WHERE id = ? AND user_id = ?
`

type SetFeedCategoryParams struct {
	CategoryID sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) SetFeedCategory(ctx context.Context, arg SetFeedCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedCategory, arg.CategoryID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setFeedFullContent = `-- name: SetFeedFullContent :execrows
UPDATE feeds SET fetch_full_content = ? WHERE id = ? AND user_id = ?
`

type SetFeedFullContentParams struct {
	FetchFullContent int64
	ID               int64
	UserID           int64
}

func (q *Queries) SetFeedFullContent(ctx context.Context, arg SetFeedFullContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedFullContent, arg.FetchFullContent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setFeedURL = `-- name: SetFeedURL :execrows
UPDATE feeds SET feed_url = ?, etag = '', last_modified = '' WHERE id = ? AND user_id = ?
`

type SetFeedURLParams struct {
	FeedUrl string
	ID      int64
	UserID  int64
}

// Clears etag/last_modified too: they belong to the old URL, so reusing them as
// conditional-GET headers against the new URL risks a spurious 304 that skips
// the new feed's content. The next poll re-fetches in full and repopulates them.
func (q *Queries) SetFeedURL(ctx context.Context, arg SetFeedURLParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedURL, arg.FeedUrl, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setFeedUserTitle = `-- name: SetFeedUserTitle :execrows
UPDATE feeds SET user_title = ? WHERE id = ? AND user_id = ?
`

type SetFeedUserTitleParams struct {
	UserTitle string
	ID        int64
	UserID    int64
}

func (q *Queries) SetFeedUserTitle(ctx context.Context, arg SetFeedUserTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedUserTitle, arg.UserTitle, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFeed = `-- name: UpdateFeed :exec
UPDATE feeds SET
  site_url = ?, title = ?, description = ?, etag = ?, last_modified = ?,
  disabled = ?, checked_at = ?, next_check_at = ?, error_count = ?, last_error = ?,
  updated_at = ?, ttl_seconds = ?
WHERE id = ? AND user_id = ?
`

type UpdateFeedParams struct {
	SiteUrl      string
	Title        string
	Description  string
	Etag         string
	LastModified string
	Disabled     int64
	CheckedAt    sql.NullInt64
	NextCheckAt  int64
	ErrorCount   int64
	LastError    string
	UpdatedAt    int64
	TtlSeconds   sql.NullInt64
	ID           int64
	UserID       int64
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeed,
		arg.SiteUrl,
		arg.Title,
		arg.Description,
		arg.Etag,
		arg.LastModified,
		arg.Disabled,
		arg.CheckedAt,
		arg.NextCheckAt,
		arg.ErrorCount,
		arg.LastError,
		arg.UpdatedAt,
		arg.TtlSeconds,
		arg.ID,
		arg.UserID,
	)
	return err
}
