// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AppSetting struct {
	Key   string
	Value string
}

type Category struct {
	ID     int64
	UserID int64
	Title  string
}

type EntriesFt struct {
	Title   string
	Content string
	Summary string
}

type Entry struct {
	ID              int64
	UserID          int64
	FeedID          int64
	Guid            string
	Url             string
	Title           string
	Author          string
	Content         string
	Summary         string
	PublishedAt     int64
	Status          string
	Starred         int64
	ReadAt          sql.NullInt64
	CreatedAt       int64
	Hash            string
	ExtractState    string
	ExtractAttempts int64
	NextExtractAt   sql.NullInt64
}

type Feed struct {
	ID               int64
	UserID           int64
	FeedUrl          string
	SiteUrl          string
	Title            string
	Description      string
	Etag             string
	LastModified     string
	Disabled         int64
	CheckedAt        sql.NullInt64
	NextCheckAt      int64
	ErrorCount       int64
	LastError        string
	CreatedAt        int64
	UpdatedAt        int64
	CategoryID       sql.NullInt64
	FetchFullContent int64
	TtlSeconds       sql.NullInt64
}

type Tombstone struct {
	FeedID    int64
	Guid      string
	DeletedAt int64
}

type User struct {
	ID        int64
	Username  string
	CreatedAt int64
}
